"use client";

import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Legend, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { models, trend } from "@/lib/demo-data";

const grid = { stroke: "#202C38", strokeDasharray: "3 3" };
const tick = { fill: "#778593", fontSize: 11, fontFamily: "var(--font-mono)" };
const tooltip = { contentStyle: { background: "#101820", border: "1px solid #2a3946", borderRadius: 10, color: "#f5f1e8", fontSize: 12 } };

export function MentionChart() { return <div className="chart-wrap"><ResponsiveContainer width="100%" height="100%"><BarChart data={models} layout="vertical" margin={{ left: 8, right: 14 }}><CartesianGrid {...grid} horizontal={false} /><XAxis type="number" tick={tick} axisLine={false} tickLine={false} /><YAxis type="category" dataKey="name" width={92} tick={tick} axisLine={false} tickLine={false} /><Tooltip {...tooltip} cursor={{ fill: "#18232c" }} /><Bar dataKey="mentions" radius={[0, 6, 6, 0]} barSize={16}>{models.map((model) => <Cell key={model.slug} fill={model.color} />)}</Bar></BarChart></ResponsiveContainer></div>; }

export function TrendChart({ lines = false }: { lines?: boolean }) { return <div className="chart-wrap"><ResponsiveContainer width="100%" height="100%">{lines ? <LineChart data={trend}><CartesianGrid {...grid} /><XAxis dataKey="date" tick={tick} axisLine={false} tickLine={false} /><YAxis tick={tick} axisLine={false} tickLine={false} /><Tooltip {...tooltip} /><Legend iconType="circle" wrapperStyle={{ fontSize: 11 }} /><Line dataKey="positive" stroke="#7CFFB2" strokeWidth={2.5} dot={false} /><Line dataKey="negative" stroke="#FF7A8A" strokeWidth={2.5} dot={false} /></LineChart> : <AreaChart data={trend}><defs><linearGradient id="mentionFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#73C7FF" stopOpacity={.32} /><stop offset="100%" stopColor="#73C7FF" stopOpacity={0} /></linearGradient></defs><CartesianGrid {...grid} /><XAxis dataKey="date" tick={tick} axisLine={false} tickLine={false} /><YAxis tick={tick} axisLine={false} tickLine={false} /><Tooltip {...tooltip} /><Area type="monotone" dataKey="mentions" stroke="#73C7FF" fill="url(#mentionFill)" strokeWidth={2.5} /></AreaChart>}</ResponsiveContainer></div>; }

export function SentimentDonut() { const data = [{ name: "Positive", value: 6914, color: "#7CFFB2" }, { name: "Neutral", value: 2332, color: "#778593" }, { name: "Negative", value: 2201, color: "#FF7A8A" }]; return <div className="donut-layout"><div className="donut"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={data} dataKey="value" innerRadius={55} outerRadius={77} paddingAngle={3} stroke="none">{data.map((item) => <Cell key={item.name} fill={item.color} />)}</Pie><Tooltip {...tooltip} /></PieChart></ResponsiveContainer><div className="donut-center"><strong>+0.49</strong><span>market score</span></div></div><div className="donut-legend">{data.map((item) => <div key={item.name}><span><i style={{ background: item.color }} />{item.name}</span><strong>{Math.round(item.value / 11447 * 100)}%</strong></div>)}</div></div>; }

export function ModelScoreChart() { return <div className="chart-wrap"><ResponsiveContainer width="100%" height="100%"><BarChart data={models}><CartesianGrid {...grid} vertical={false} /><XAxis dataKey="name" tick={tick} axisLine={false} tickLine={false} /><YAxis domain={[-1, 1]} tick={tick} axisLine={false} tickLine={false} /><Tooltip {...tooltip} /><Bar dataKey="score" radius={[6, 6, 0, 0]}>{models.map((model) => <Cell key={model.slug} fill={model.color} />)}</Bar></BarChart></ResponsiveContainer></div>; }
