"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { ArrowRight, Check, ChevronDown, SlidersHorizontal } from "lucide-react";
import { models } from "@/lib/demo-data";
import { Delta, DemoBadge, Eyebrow } from "./ui";
import { TrendChart } from "./charts";

export function ComparePage() {
  const [selected, setSelected] = useState(models.map((model) => model.slug)); const [sort, setSort] = useState("mentions");
  const visible = useMemo(() => models.filter((model) => selected.includes(model.slug)).sort((a, b) => sort === "score" ? b.score - a.score : sort === "growth" ? b.growth - a.growth : b.mentions - a.mentions), [selected, sort]);
  return <div className="page compare-page"><div className="topbar"><DemoBadge /><span>{visible.length} models selected</span></div><header className="page-header compact-header"><div><Eyebrow>Side-by-side intelligence</Eyebrow><h1>Compare the<br /><span>signal.</span></h1></div><p>Separate attention from affinity. Contrast conversation volume, perception, engagement, and recurring feedback.</p></header><section className="compare-controls panel"><div><SlidersHorizontal /><span>Models</span>{models.map((model) => <button key={model.slug} className={selected.includes(model.slug) ? "selected" : ""} onClick={() => setSelected((items) => items.includes(model.slug) ? items.length > 2 ? items.filter((item) => item !== model.slug) : items : [...items, model.slug])}><i style={{ background: model.color }} />{model.name}{selected.includes(model.slug) && <Check />}</button>)}</div><label>Sort by<select value={sort} onChange={(event) => setSort(event.target.value)}><option value="mentions">Mentions</option><option value="score">Sentiment score</option><option value="growth">Growth</option></select><ChevronDown /></label></section><section className="comparison-grid">{visible.map((model) => <article className="comparison-card panel" key={model.slug} style={{ "--model-color": model.color } as React.CSSProperties}><header><i>{model.monogram}</i><span><small>{model.vendor}</small><h2>{model.name}</h2></span><Link href={`/models/${model.slug}`}><ArrowRight /></Link></header><div className="big-score"><span>Sentiment score</span><strong>+{model.score}</strong><Delta value={model.growth} /></div><div className="sentiment-stack"><div style={{ width: `${model.positive / model.mentions * 100}%` }} /><div style={{ width: `${model.neutral / model.mentions * 100}%` }} /><div style={{ width: `${model.negative / model.mentions * 100}%` }} /></div><div className="comparison-stats"><div><span>Mentions</span><strong>{model.mentions.toLocaleString()}</strong></div><div><span>Positive</span><strong>{(model.positive / model.mentions * 100).toFixed(1)}%</strong></div><div><span>Negative</span><strong>{(model.negative / model.mentions * 100).toFixed(1)}%</strong></div><div><span>Avg. engagement</span><strong>{model.engagement}</strong></div></div><div className="feedback-columns"><div><span>Strengths</span>{model.strengths.map((item) => <em key={item}>+ {item}</em>)}</div><div><span>Complaints</span>{model.weaknesses.map((item) => <em key={item}>− {item}</em>)}</div></div></article>)}</section><section className="panel compare-trend section-block"><div className="chart-title"><div><h2>Market polarity</h2><p>Combined positive and negative conversation volume</p></div><span>7 days</span></div><TrendChart lines /></section></div>;
}

