import type { Metadata } from "next";
import { CheckCircle2, Database, Fingerprint, Gauge, SearchCheck, ShieldCheck, TriangleAlert } from "lucide-react";
import { DemoBadge, Eyebrow } from "@/components/ui";
import { ingestionRuns } from "@/lib/demo-data";
export const metadata: Metadata = { title: "Methodology", description: "How Codex Signalist collects, classifies, and aggregates model sentiment." };

const steps = [
  { n: "01", icon: SearchCheck, title: "Collect", text: "Each hour, the official X API v2 recent-search endpoint retrieves English-language posts using model-specific queries. Reposts are excluded." },
  { n: "02", icon: Fingerprint, title: "Resolve", text: "Specific aliases map posts to the model registry. Ambiguous names such as “Sol” and “Opus” require nearby AI or developer context." },
  { n: "03", icon: Gauge, title: "Analyze", text: "Every model mention receives its own sentiment label, normalized score, confidence, explanation, themes, strengths, and weaknesses." },
  { n: "04", icon: Database, title: "Aggregate", text: "PostgreSQL queries calculate volume, unweighted perception, engagement, and topic trends without letting a single viral post dominate." },
];
export default function Methodology() { return <div className="page methodology-page"><div className="topbar"><DemoBadge /><span className="method-version">Methodology v1.0</span></div><header className="page-header narrow"><div><Eyebrow>Transparent by design</Eyebrow><h1>From conversation<br /><span>to signal.</span></h1></div><p>Codex Signalist is built to make perception analytics legible, reproducible, and honest about its limits.</p></header><section className="method-steps">{steps.map(({ n, icon: Icon, title, text }) => <article key={n} className="panel"><span>{n}</span><Icon /><h2>{title}</h2><p>{text}</p></article>)}</section><section className="method-grid section-block"><article className="panel method-card"><Eyebrow>Classification</Eyebrow><h2>What the labels mean</h2><dl><div><dt className="positive-text">Positive</dt><dd>Clear praise, preference, successful results, or favorable comparison directed at a model.</dd></div><div><dt className="negative-text">Negative</dt><dd>Criticism, failure, frustration, or an unfavorable comparison directed at a model.</dd></div><div><dt>Neutral</dt><dd>Factual reporting, mixed or weak signals, benchmark results without a strong judgment.</dd></div></dl></article><article className="panel method-card formula"><Eyebrow>Score</Eyebrow><h2>A bounded perception measure</h2><div><span>positive − negative</span><hr /><span>all classified mentions</span></div><p>Scores run from −1.0 to +1.0. The primary score is unweighted; engagement-weighted data is shown separately.</p></article></section><section className="limitations panel section-block"><TriangleAlert /><div><Eyebrow>Important limitations</Eyebrow><h2>This is conversation data—not ground truth.</h2><p>X users are not representative of all model users. Search coverage, deleted posts, private accounts, API limits, sarcasm, coordinated promotion, and language constraints can affect results. Sentiment describes expressed perception, not objective model quality.</p></div></section><section className="run-history section-block"><div className="section-heading"><div><Eyebrow>Ingestion diagnostics</Eyebrow><h2>Recent pipeline activity</h2></div><span className="health-pill"><ShieldCheck />All systems operational</span></div><div className="panel runs-table"><div className="table-head"><span>Run</span><span>Started</span><span>Status</span><span>New posts</span><span>Pages</span><span>Duration</span></div>{ingestionRuns.map((run) => <div key={run.id}><strong>{run.id}</strong><span>{run.time}</span><span className={`run-status ${run.status.toLowerCase()}`}><CheckCircle2 />{run.status}</span><span>{run.newPosts}</span><span>{run.pages}</span><span>{run.duration}</span></div>)}</div></section></div>; }

